### ISSUE TITLE
AppImage crash on Fedora

### ISSUE THREAD

**Issue by brneor** [the-via/releases#139]
Fedora 35 fresh install. It happens under Wayland and Xorg. Log:

```
./via-1.3.1-linux.AppImage
Beginning of file
Finish Imports
Requesting lock
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
promppting linux access
390cd24a6ad30bec63967065a5898337
loading app url
10:26:19.684 › Checking for update
10:26:21.156 › Update for version 1.3.1 is not available (latest version: 1.3.1, downgrade is disallowed).
10:26:21.157 › checkForUpdatesAndNotify called, downloadPromise is null
[9104:1112/102622.739920:FATAL:gpu_data_manager_impl_private.cc(986)] The display compositor is frequently crashing. Goodbye.
[1]    9104 trace trap (core dumped)  ./via-1.3.1-linux.AppImage
```

**Comment by nerd** [comment]
+1, also happens to me on gentoo

**Comment by xoxoMarzy** [comment]
+1, Fedora 35 Silverblue. Same issue

**Comment by dzintars** [comment]
Similar on Fedora 34 Wayland ONLY (Sway)
```bash
» ~/Applications/via-1.3.1-linux_757e184e566f97b0bf1df47839d99a5a.AppImage
/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
Beginning of file
Finish Imports
Requesting lock
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
promppting linux access
390cd24a6ad30bec63967065a5898337

===
In order to communicate with your keyboard we need to add a udev rule which requires root permissions. Continue?
Yes, Continue
===

Error: No polkit authentication agent found.
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12) {
  killed: false,
  code: 127,
  signal: null,
  cmd: `cd "/home/dzintars"; "/usr/bin/pkexec" --disable-internal-agent /bin/bash -c "echo SUDOPROMPT; printf 'KERNEL==\\"hidraw*\\", SUBSYSTEM==\\"hidraw\\", MODE=\\"0666\\", TAG+=\\"uaccess\\", TAG+=\\"udev-acl\\"' > /etc/udev/rules.d/92-viia.rules && udevadm control --reload-rules && udevadm trigger"`
}
```

**Comment by nabulator** [comment]
> Similar on Fedora 34 Wayland ONLY (Sway)

I am running the tar'd binary  (not the app image) on Arch with Sway and had the same problem. @dzintars solution worked for me

**Comment by Parent5446** [comment]
Has anyone found a workaround for the original crash issue above (i.e., the `The display compositor is frequently crashing. Goodbye.`)? I'm still experiencing it on Fedora 35.

**Comment by Parent5446** [comment]
Nevermind found a workaround. Run the app with `--no-sandbox`

**Comment by Hund** [comment]
I have the same issue on Fedora:

```bash
$ via
Beginning of file
Finish Imports
Requesting lock
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
promppting linux access
390cd24a6ad30bec63967065a5898337
[2034:0109/190043.709884:FATAL:gpu_data_manager_impl_private.cc(986)] The display compositor is frequently crashing. Goodbye.
zsh: trace trap (core dumped)  via
```

**Comment by sisyphusion** [comment]
+1 fresh Fedora 35 install, X11 and Wayland

**Comment by Hund** [comment]
I solved it by using VIAL instead. It's an open source version alternative to VIA. :)

**Comment by Parent5446** [comment]
Interesting. Is VIAL just cross-compatible with VIA? Or do you have to install new firmware for it?

**Comment by Hund** [comment]
> Interesting. Is VIAL just cross-compatible with VIA? Or do you have to install new firmware for it?

No new firmware required.

**Comment by IvarWithoutBones** [comment]
Can reproduce this on NixOS as well, using the deb.

**Comment by duxeyo** [comment]
happens on arch compton xfce

**Comment by quasigod-io** [comment]
Happening on Arch with i3. Doesn't matter whether I'm running Picom or not either.

**Comment by mscharley** [comment]
Also having this issue on Arch with Cinnamon on X11. `--no-sandbox` got it working for me for now.

**Comment by SeedyROM** [comment]
+1 Arch with Manjaro and XFCE

**Comment by dgva** [comment]
On EndeavourOS X11, `--no-sanbox` works too.

**Comment by dzintars** [comment]
Just leaving little finding in any case.
If running SwayWM with `xwayland disable`, VIA fails to start.
Enabling XWayland helps. But not the solution I would like to use.

**Comment by kmanwar89** [comment]
I'm on Pop!_OS, brand new install. Never had issues with VIA before, but on a fresh install I'm receiving the same Appimage crash.

Appending _--no-sandbox_ also works for me.

Is a fix in progress?
