### ISSUE TITLE
Command BACKLIGHT_CONFIG_GET_VALUE has bad response

### ISSUE THREAD

**Issue by lsxfhao** [the-via/releases#251]
**Describe the bug**
When I use the app online/offline version, my corne keyboard is not recognized. I have error message in the console:
```
Loading keyboard failed: Error: Receiving incorrect response for command
    at KeyboardAPI._hidCommand (index-ba3543d9.js:1:19736)
    at async KeyboardAPI.flushQueue (index-ba3543d9.js:1:18862)
```
Also the error message in VIA error tab
```
11:10:50.355
    Vid: 0x4653
    Pid: 0x0001
    Command name: BACKLIGHT_CONFIG_GET_VALUE
    Command: 8 2 1
    Response: 255 2 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
----------------------------------
11:10:50.369
    Vid: 0x4653
    Pid: 0x0001
    Command name: BACKLIGHT_CONFIG_GET_VALUE
    Command: 8 2 2
    Response: 255 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
---------------------------------
11:10:50.371
    Vid: 0x4653
    Pid: 0x0001
    Command name: BACKLIGHT_CONFIG_GET_VALUE
    Command: 8 2 3
    Response: 255 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```

This only happens after the major UI change of VIA. I can use the old one couple of weeks before.

**To Reproduce**
1. Open VIA
2. Plug in my corne keyboard.
3. See error

**Expected behavior**
Keymap recognized.

**Screenshots**
Don't know how to upload.

**VIA Version**
- [x] I am using https://usevia.app/
- [x] I am using the latest release of the desktop app from https://github.com/the-via/releases/releases/latest

**Keyboard firmware VIA protocol**
12

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, macOS, Windows] Windows
 - Browser (if applicable) [e.g. chrome, safari] Chrome

**Custom json definition?**
- [ ] I am loading a custom json definition using the designer tab

**Sanity checks**
- [x] I have tried connecting the keyboard directly to the computer (i.e. not using a USB hub)
- [x] I have flashed the latest firmware from https://www.caniusevia.com/docs/download_firmware

**Additional context**
I can use the default via keymap from qmk, but I cannot use my own keymap. I have checked the rules.mk and config.h, the only change I made is add "#define DYNAMIC_KEYMAP_LAYER_COUNT 5" to get more layer. It was working before.

**Comment by lsxfhao** [comment]
Update on release 3.0.0:
The error still exists, but the keyboard is recognized, and basic feature is usable. So far it's enough for me.
I'm not using any light or RGB on my keyboard, but VIA seems very insistent to get the light config, which seems unnecessary.

**Comment by idank** [comment]
Same here. Getting these errors on a crkbd/rev1:via when RGBLIGHT_ENABLE is not defined.

Everything works fine but the errors are annoying. Is there a way to fix this?

**Comment by rickdgray** [comment]
I have the same issue with my kbdfans kbdpad mark ii

**Comment by AdrianBonpin** [comment]
Same here with both R2G and rev1

I don't really mind not having "good" rgb, but it would be nice for this to get fixed to get some nicer effects and control with via

**Comment by udirona** [comment]
Same here with a R2G. But i could find out that this is a missmatch between the compiled firmware and the crkbd.json of the via app. In this config it says "qmk_rgblight" but this feature is not active in the firmware for the corne. so i changed this setting to "qmk_rgb_matrix" and the error is gone.
