### ISSUE TITLE
bad response from Command DYNAMIC_KEYMAP_GET_ENCODER

### ISSUE THREAD

**Issue by WarbirdXBL** [the-via/releases#258]
bad response from Command DYNAMIC_KEYMAP_GET_ENCODER

**Describe the bug**
getting 16 errors (8 pairs) when saving Keychron Q6 layout.
does not seem to inhibit layout modifiability.

**To Reproduce**
1. Go to 'https://usevia.app/'.
2. Authorise keyboard.
3. Save layout to disk.
4. See error: 8 of these two identical error pairs

13:33:43.973

	Command Name: DYNAMIC_KEYMAP_GET_ENCODER
	Command: 20 0 0 0
	Response: 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

	Device: Keychron Q6
	Vid: 0x3434
	Pid: 0x0161

13:33:43.999

	Error: Receiving incorrect response for command
	at KeyboardAPI._hidCommand (https://usevia.app/assets/index-57542d2d.js:3:9407)
	at async KeyboardAPI.flushQueue (https://usevia.app/assets/index-57542d2d.js:3:8661)

	Device: Keychron Q6
	Vid: 0x3434
	Pid: 0x0161

**Expected behavior**
Save the loyout with no errors.

**Screenshots**
see errors

**VIA Version**
- [x] I am using https://usevia.app/
- [ ] I am using the latest release of the desktop app from https://github.com/the-via/releases/releases/latest

**Keyboard firmware VIA protocol**
VIA Firmware Protocol = 9

**Desktop (please complete the following information):**
 - OS: [Windows 10 PRO]
 - Browser: Chrome

**Custom json definition?**
- [X] I am loading a custom json definition using the designer tab
I have tried both, eg. the Q6 is recognized by VIA.

**Sanity checks**
- [X] I have tried connecting the keyboard directly to the computer (i.e. not using a USB hub)
- [ ] I have flashed the latest firmware from https://www.caniusevia.com/docs/download_firmware
Q6 ordered directly from Keychron Apr 2023.

**Additional context**

**Comment by kenjaninja** [comment]
I'm getting the same issue on the Keychron V6, 8 pairs of errors when saving the layout.

**Comment by undefinedbyzero** [comment]
Same here with a Keychron Q3, 16 Errors

**Comment by L1zardo** [comment]
I'm also getting this plus another 19 errors.

Device: Keychron Q2
Vid: 0x3434
Pid: 0x0111

**Comment by bsg62** [comment]
Same problem with a new Q1, 16 errors. Web or Desktop doesn't matter and does not save the layout. I wanted to remap caps to left ctrl, does not work.

Command Name: DYNAMIC_KEYMAP_GET_ENCODER
Command: 20 0 0 0
Response: 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

Device: Keychron Q1
Vid: 0x3434
Pid: 0x0107

**Comment by miletiko** [comment]
Same problem Q1, 16 errors

Command Name: DYNAMIC_KEYMAP_GET_ENCODER
Command: 20 0 0 0
Response: 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

Device: Keychron Q1
Vid: 0x3434
Pid: 0x0107

**Comment by CameronJRAllan** [comment]
Same here with a Q2:

Command Name: DYNAMIC_KEYMAP_GET_ENCODER
Command: 20 0 0 0
Response: 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
Device: Keychron Q2
Vid: 0x3434
Pid: 0x0113

**Comment by kamikazeedriver** [comment]
Same list of errors on a Keychron V6 with knob.

I've also noticed that on Lighting, the Rainbow Beacon, and all the settings after it, are the same.  

My V5 works great, but this v6, I'm not convinced yet.

**Comment by alaborderie** [comment]
Hey just want to add I have the same issue on a Keychron Q8.

It used to work like a few months ago, maybe a year ago, last time I edited it.
I tried using both AppImage and browser version using chromium

[VIA-app-errors.csv](https://github.com/the-via/releases/files/12474352/VIA-app-errors.csv)

**Comment by kamikazeedriver** [comment]
I was able to fix my problem with a firmware flash, but I can't remember how I was able right now.  
All I remember is after getting no assistance from Keychron, I joined their discord, and searched the comments for my problem.
One of the results was from one of the Keychron team saying to do something, which would allow me to install the firmware.
After installing the firmware, all was well.

**Comment by kamikazeedriver** [comment]
> Hey just want to add I have the same issue on a Keychron Q8.
> 
> It used to work like a few months ago, maybe a year ago, last time I edited it. I tried using both AppImage and browser version using chromium
> 
> [VIA-app-errors.csv](https://github.com/the-via/releases/files/12474352/VIA-app-errors.csv)

Ok I remember more about what happened.  
So yeah, you do the firmware and that fixes the problem.
The only problem is, some people run into an issue when installing the firmware.

So first, for your keyboard, go here: [](https://www.keychron.com/blogs/archived/how-to-factory-reset-or-flash-your-qmk-via-enabled-keychron-q8-keyboard)

I did all this, but then on STEP 7, I kept encountering an error.  
That was when I reached out to Keychron, but got no reply.

If you also encounter an error on Step 7.  You'll know it because the yellow text in that window won't say what the keychron website says it should say.

So then I went to their discord, searched for the Error I was getting, and saw others had encountered it to, and one of them was answered by some Keychron team member about some utility or something you had to do.  
I think it was uninstalling some driver that seems to affect many systems.  Just search though, you'll find it.

Once I uninstalled that driver, everything worked fine, I was able to update the firmware, and use my keyboard like normal.  
That was months ago.

**Comment by kenjaninja** [comment]
Okay, so I found the discord conversation kamikazeedriver was talking about, and was able to fix the issue I was having. 
Here is the [link](https://discord.com/channels/673730324047462449/673744077912801300/1099320528113770526) to the first message of the original conversation.

I'm not too familiar with driver stuff, but in my case, it seems like the PC inadvertently uses an unrelated driver called "Guillemot" to drive(?) the keyboard. This causes the error we're seeing (I think).

## Steps I took
### Diagnosis
1. Go thru the [instructions](https://www.keychron.com/blogs/archived/how-to-factory-reset-or-flash-your-qmk-via-enabled-keychron-v6-keyboard) to factory reset the keyboard, up to **Step 7**, putting the keyboard into DFU mode. (I'll use the V6 instructions, since that's what I have)
3. At this point, in QMK Toolbox, the keyboard _should_ display as **STMicroelectronics STM32 BOOTLOADER**, but mine shows as **Guillemot STM DFU Device**.
![Untitled](https://github.com/the-via/releases/assets/12107190/72b071e4-daa2-42a7-9d68-869b2541412c)

### Solution
To resolve the issue, we need to delete the Guillemot driver. I derived these steps from this [Pimax forum post](https://community.openmr.com/t/pimaxvr-troubleshooting-wip/37879/3); funnily enough, it seems like they ran into the same issue we're having.
1. First, delete these two folders:
  `C:\Program Files\Guillemot`
  `C:\Program Files(x86)\Guillemot`
2. Go to **Device Manager** and uninstall **Guillemot STM DFU Device** under **Sound, video and game controllers**. _Make sure **Delete the driver software for this device** is checked_.
![50e7e37ea9b9fe8b9ab82e659902ee0a0dfe5b3c](https://github.com/the-via/releases/assets/12107190/b5ed2482-2403-429d-9223-a62bec1baae8)
3. Go back and follow steps 3 thru 7 of the Keychron factory reset instructions (unplug -> open QMK -> install drivers -> put keyboard in DFU mode)
4. If the driver was deleted successfully, QMK Toolbox should now display the keyboard as **STMicroelectronics STM32 BOOTLOADER**
![image](https://github.com/the-via/releases/assets/12107190/b1efc436-faa3-416f-9adc-19f6647232b5)
5. You can now flash the keyboard and continue with the factory reset instructions.
6. At this point, I was able to save my layout in VIA without errors.

Hopefully this helps. Happy Halloween :)

**Comment by Penpen7** [comment]
When I used my Keychron Q2, I encountered the same problem, but I was able to solve it!
 I simply flashed the firmware by referring to this [document](https://www.keychron.com/blogs/archived/how-to-factory-reset-or-flash-your-qmk-via-enabled-keychron-q2-keyboard).

**Comment by 2zqa** [comment]
I am using a dock to connect my laptop to a monitor and ethernet etc, and I fixed this error by plugging my keyboard directly in my laptops USB ports instead of the dock.

**Comment by silviu-negoita** [comment]
> I am using a dock to connect my laptop to a monitor and ethernet etc, and I fixed this error by plugging my keyboard directly in my laptops USB ports instead of the dock.

This! thank you! This was my issue.. I always had the keyboard through to docking connect...
