### ISSUE TITLE
Is Via actually open source?

### ISSUE THREAD

**Issue by FrankSalmick** [the-via/releases#26]
Via is crashing when I flash a Quefrency with the default rev1 firmware with the via keymap. I'm not sure what is missing, but I see this in my log:

```[2020-05-04 10:19:06.728] [error] {
  constructor: 'TypeError',
  stack: "TypeError: Cannot read property 'replace' of undefined\n" +
    '    at J (file:///C:/Users/frank/AppData/Local/Programs/via/resources/app.asar/app/dist/renderer.prod.js:154:19)\n' +
    '    at file:///C:/Users/frank/AppData/Local/Programs/via/resources/app.asar/app/dist/renderer.prod.js:154:1831\n' +
    '    at renderWithHooks (C:\\Users\\frank\\AppData\\Local\\Programs\\via\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:16260:18)\n' +
```

This error is making me think I the default firmware is missing a value somewhere, but since the app has already been bundled I can't open the devtools for context about what variable is undefined. Is it possible to compile my own dev version of Via? If not can someone help me figure out why the default firmware doesn't work? Everything is fine except that when I try to configure it in Via the screen just turns blue.

**Comment by FrankSalmick** [comment]
After looking around more I found https://github.com/the-via/reader, which I think is it, but it seems to be lacking any build instructions, are those found anywhere? I did the usual `npm install` and `electron ./dist` (and `electron .`) but nothing opened.

**Comment by jrop** [comment]
I came here looking for the same thing: the source.  It is not immediately obvious if this project is actually open-source, or not.  @olivia?

From what I can tell scouring the internet, it appears that at one point VIA was open source, but is it still, that is the question.

**Comment by ifohancroft** [comment]
I cam here to ask the same thing.

**Comment by jezdez** [comment]
Seconded, knowing where to find the source code would be appreciated and would provide some peace of mind while loading random binaries to my devices.

**Comment by xtaran** [comment]
Came here for the very same reason. :-)

Potentially interested in building packages for Debian. But for that, I'd need to know:

* the source code
* the exact license
* preferably some minimal build instructions

**Comment by rbange** [comment]
This might be especially helpful as PR's for new keyboards are only pulled if their corresponding QMK PR is merged, which can take a very long time. 
Importing the JSON's into VIA manually everytime is not really desirable for a daily driver keyboard.

**Comment by PLJNS** [comment]
I would also like to know this. From what I can tell, the reader repo is something related to VIA, but I don't believe it's the whole thing. It's a great application, but I'm worried it's foolish to use a keyboard configurator that you cannot confirm isn't malware.

**Comment by jezdez** [comment]
FWIW this is a duplicate of #13 and #65.

**Comment by jezdez** [comment]
https://github.com/the-via/keyboards/issues/491 is also a pretty interesting discussion.

**Comment by ifohancroft** [comment]
Sorry, I've been meaning to post this for a while now:

I spoke with Olivia on Discord about it and asked her. This is what she said about it:

"A portion of VIA is open source, which handles the parsing and generation of the keyboard configuration files. The GUI part however is currently not open sourced, but at some point I intend to open it up."

**Comment by jezdez** [comment]
> Sorry, I've been meaning to post this for a while now:
> 
> I spoke with Olivia on Discord about it and asked her. This is what she said about it:
> 
> "A portion of VIA is open source, which handles the parsing and generation of the keyboard configuration files. The GUI part however is currently not open sourced, but at some point I intend to open it up."

Thanks @ifohancroft for sharing this, it's much appreciated!

**Comment by danielo515** [comment]
> The GUI part however is currently not open sourced, but at some point I intend to open it up

I'm really interested to know what are the reasons to not have it open source, and when is this planned.

**Comment by ifohancroft** [comment]
> > Sorry, I've been meaning to post this for a while now:
> > I spoke with Olivia on Discord about it and asked her. This is what she said about it:
> > "A portion of VIA is open source, which handles the parsing and generation of the keyboard configuration files. The GUI part however is currently not open sourced, but at some point I intend to open it up."
> 
> Thanks @ifohancroft for sharing this, it's much appreciated!

I have no idea about her reasoning behind this, but what I do is this:
I open source and want to open source everything I write, however, I don't release stuff until I consider them ready. I guess releasing the output of something versus releasing the code is different but I am guessing she may have not considered the GUI ready or may have wrote it in the beginning just so it works and wants to refactor it before releasing it? After all, people will judge you for the code you wrote if it's not good.

**Comment by danielo515** [comment]
Interesting point @ifohancroft.
I have been there too and I think that, if you don't have time to put into something you want to open source maybe just release it as it is and let others help.
I don't think anyone is going to judge you by the code you write (but who knows, there are all kind of people), but a lot of people is eager (or they say so) to collaborate, which may speed things up.

At the end of the day, it is better to release something (in this context I mean releasing the code to be OS) than trying to reach perfection and not deliver anything.

That said, I respect people for not wanting to OS everything, but I am just curious about the reasons, since the tool is already free and compatible with dozens of keyboards.
